# Generated by Django 2.2.12 on 2021-10-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=8, verbose_name='Descripción')),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Grados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descgrado', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'grado',
                'verbose_name_plural': 'grados',
                'db_table': 'grados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreapellido', models.CharField(help_text='Ingrese APELLIDOS + NOMBRES', max_length=400)),
                ('codigofun', models.CharField(max_length=10, unique=True, verbose_name='Cod.Funcionario')),
                ('cua', models.CharField(max_length=10, unique=True)),
                ('departamento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='CuaApp.Departamento')),
                ('estado', models.ForeignKey(blank=True, db_column='estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CuaApp.Estado')),
                ('grado', models.ForeignKey(db_column='grado', on_delete=django.db.models.deletion.DO_NOTHING, to='CuaApp.Grados')),
            ],
            options={
                'verbose_name': 'Identificación',
                'verbose_name_plural': 'Identificaciones',
                'db_table': 'identificacion',
            },
        ),
    ]
