# Generated by Django 3.0.6 on 2020-06-22 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('idCondominio', models.IntegerField(primary_key=True, serialize=False)),
                ('razonSocial', models.CharField(max_length=200)),
                ('giro', models.CharField(max_length=200)),
                ('telefonoRedFija', models.CharField(max_length=20)),
                ('telefonoMovil', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPerfil', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.IntegerField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=1)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidoPaterno', models.CharField(max_length=45)),
                ('apellidoMaterno', models.CharField(max_length=45)),
                ('nacionalidad', models.CharField(max_length=45)),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField(unique=True)),
                ('estadoUsuario', models.BooleanField()),
                ('contrasenia', models.CharField(max_length=100)),
                ('fechaCreacion', models.DateField()),
                ('fechaModificacion', models.DateField()),
                ('fechaEliminación', models.DateField()),
                ('idCondominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.Condominio')),
                ('idPerfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.Perfil')),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('idInteres', models.IntegerField(primary_key=True, serialize=False)),
                ('factorInteres', models.FloatField()),
                ('fechaVigenciaDesde', models.DateField()),
                ('fechaVigenciaHasta', models.DateField()),
                ('idCondominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.Condominio')),
            ],
        ),
    ]
