# Generated by Django 3.0.6 on 2020-06-22 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCondominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCuentaCondominio', models.IntegerField(unique=True)),
                ('razonSocial', models.CharField(max_length=255)),
                ('numeroCuenta', models.CharField(max_length=255)),
                ('bancoEmisor', models.CharField(max_length=255)),
                ('observacion', models.CharField(max_length=255)),
                ('fechaCreacion', models.DateField()),
                ('fechaModificacion', models.DateField()),
                ('fechaEliminación', models.DateField()),
                ('idCondominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.Condominio')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCuentaCondominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTransaccion', models.IntegerField(unique=True)),
                ('fecha', models.DateField()),
                ('asunto', models.IntegerField()),
                ('monto', models.IntegerField()),
                ('codigoReferencia', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('fechaCreacion', models.DateField()),
                ('fechaModificacion', models.DateField()),
                ('fechaEliminación', models.DateField()),
                ('idCuentaCondominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.CuentaCondominio')),
            ],
        ),
    ]
