# Generated by Django 3.0.6 on 2020-06-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0004_condominio_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='rut',
            field=models.IntegerField(default=11111111),
        ),
    ]
