# Generated by Django 3.0.6 on 2020-06-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0006_auto_20200623_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condominio',
            options={'verbose_name': 'condominio', 'verbose_name_plural': 'condominios'},
        ),
        migrations.AlterField(
            model_name='cuentacondominio',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
