# Generated by Django 3.0.6 on 2020-06-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0008_auto_20200623_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='fechaNacimiento',
            new_name='fecha_Nacimiento',
        ),
    ]
