# Generated by Django 3.0.6 on 2020-06-23 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0010_auto_20200623_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('idPersona', models.IntegerField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('nombres', models.CharField(max_length=45)),
                ('apellido_Paterno', models.CharField(max_length=45)),
                ('apellido_Materno', models.CharField(max_length=45)),
                ('telefono', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=45)),
                ('fecha_Nacimiento', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idPersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.Propietario'),
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
