# Generated by Django 3.0.6 on 2020-06-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0011_auto_20200623_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='idPersona',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut'),
        ),
    ]
