# Generated by Django 3.0.6 on 2020-06-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0013_auto_20200623_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='correo',
            field=models.EmailField(default=111111111, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propietario',
            name='idPersona',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut'),
        ),
    ]
