# Generated by Django 3.0.6 on 2020-06-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0014_auto_20200623_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vivienda',
            name='idCondominio',
        ),
        migrations.RemoveField(
            model_name='vivienda',
            name='numero',
        ),
        migrations.AddField(
            model_name='vivienda',
            name='torre',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='codigoVivienda',
            field=models.CharField(max_length=12),
        ),
    ]
