# Generated by Django 3.0.6 on 2020-06-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0015_auto_20200623_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='idPersona',
            new_name='id_Propietario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='idCondominio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='idPerfil',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasenia',
            field=models.CharField(max_length=100, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.CharField(max_length=10, verbose_name='Rut Usuario'),
        ),
    ]
