# Generated by Django 3.0.6 on 2020-06-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0016_auto_20200623_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido_Paterno',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nacionalidad',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propietario',
            name='idPersona',
            field=models.CharField(help_text='Entre RUT en formato 99999999-X', max_length=10, primary_key=True, serialize=False, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_Eliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.CharField(help_text='Entre RUT en formato 99999999-X', max_length=10, verbose_name='Rut Usuario'),
        ),
    ]
