# Generated by Django 3.0.6 on 2020-06-24 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0018_auto_20200623_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='idVivienda',
            field=models.ForeignKey(default=11111, on_delete=django.db.models.deletion.CASCADE, to='condominio.Vivienda'),
            preserve_default=False,
        ),
    ]
