# Generated by Django 3.0.6 on 2020-06-24 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0020_auto_20200624_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriagastocomun',
            old_name='Descripción_Categoria',
            new_name='Descripcion_Categoria',
        ),
        migrations.RenameField(
            model_name='subcategoriagastocomun',
            old_name='Descripción_Subcategoria',
            new_name='Descripcion_Subcategoria',
        ),
    ]
