# Generated by Django 3.0.6 on 2020-06-25 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0022_auto_20200624_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastocomun',
            name='idCondominio',
        ),
    ]
