# Generated by Django 2.2.12 on 2021-09-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=8, verbose_name='Descripción')),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grados',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descgrado', models.CharField(max_length=100, verbose_name='DescripciOn')),
            ],
            options={
                'db_table': 'grados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreapellido', models.CharField(max_length=400, verbose_name='Nombre - Apellido')),
                ('codigofun', models.CharField(max_length=10, unique=True, verbose_name='Código Funcionnario')),
                ('cua', models.CharField(max_length=10, unique=True, verbose_name='Código C.U.A.')),
            ],
            options={
                'db_table': 'Identificacion',
                'managed': False,
            },
        ),
    ]
