# Generated by Django 2.2.12 on 2021-09-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cua', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='grados',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
